### PR TITLE
Code optimizing

### PR DESCRIPTION
**Pull request by portlek**
> Remove un-necessary files
> Code optimizing
> Imports optimizing

### CODE REVIEW

**Comment by xuancat0208** [comment]
FIXME: 25/12/2019 Casting 'nbtBase' to 'CodeNBTList' will produce 'ClassCastException' for any non-null value
No!!!
Only came in Basic Object / CodeNBTList(NBTList) / CodeNBTCompound(NBTCompound)

**Comment by portlek** [comment]
If there is an error about "this code can throw ClassCastException" it means it can be. You can say this but the programming does not exactly work like that.

**Comment by portlek** [comment]
If the code says "it can be" you have to think like "it will be"

**Comment by xuancat0208** [comment]
Alright. Indeed, the best solution is the best.

**Comment by portlek** [comment]
You have to be strict when you are creating a library that can use by everyone.

**Comment by xuancat0208** [comment]
I know, I'm reviewing all the code.
And ensure 100% no problems in the 1.15 test.

**Comment by xuancat0208** [comment]
So far, no errors have occurred, which is a good thing

**Comment by xuancat0208** [comment]
Off topic, NBTList <T> is intentional.
I thought it was more convenient to understand the type of list XD

**Pull request merged**
